name: 04 Deploy React on Heroku

on:
  push:
    branches: [ master ]
    paths:
    - '04_reactapp/**'
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 04_reactapp
    name: Build and Deploy to Surge
    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: Install Web Packages
      run: npm install
    - name: Build App
      run: npm run build
    - uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "demo-react2"
        heroku_email: "zeeshanhanif@panacloud.com"
        usedocker: false
        appdir: "build"