name: 05 Deploy React on Surge with Yarn

on:
  push:
    branches: [ master ]
    paths:
    - '05_reactappwithyarn/**'
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 05_reactappwithyarn
    name: Build and Deploy to Surge
    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - name: Change Directory
      run: cd ./05_reactappwithyarn
      
    - uses: borales/actions-yarn@v2.0.0
      with: 
        cmd: install

    - name: Build App
      run: yarn build

    - name: Install Surge
      run: yarn global add surge
    - name: Run Surge
      run: surge ./build zeeshan-reactupdated.surge.sh --token ${{secrets.SURGE_TOKEN}}
