name: Deploy Web App

on:
  push:
    branches: [ master ]
    paths:
    - '01_staticweb/**'
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to Surge
    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./01_staticweb/ zeeshanhanif.surge.sh --token ${{secrets.SURGE_TOKEN}}
