name: 04 Deploy React App

on:
  push:
    branches: [ master ]
    paths:
    - '04_reactapp/**'
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 04_reactapp
    name: Build and Deploy to Surge
    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: Install Web Packages
      run: npm install
    - name: Build App
      run: npm run build
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./build zeeshan-react.surge.sh --token ${{secrets.SURGE_TOKEN}}
